### ISSUE TITLE
crictl cannot pull image just by name

### ISSUE THREAD

**Issue by gouyang** [kubernetes-incubator/cri-tools#214] opened 2017-12-08 03:23 UTC
crictl cannot pull image just by name, it need to specify the registry like `docker.io/library/redis:alpine`
```
[root@fedora27 cri-o]# crictl -D pull docker.io/library/redis:alpine
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:docker.io/library/redis:alpine,},Auth:nil,SandboxConfig:nil,} 
DEBU[0006] PullImageResponse: &PullImageResponse{ImageRef:docker.io/library/redis:alpine,} 
Image is update to date for docker.io/library/redis:alpine

[root@fedora27 cri-o]# crictl -D pull redis:alpine
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:redis:alpine,},Auth:nil,SandboxConfig:nil,} 
DEBU[0000] PullImageResponse: nil                       
FATA[0000] pulling image failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image 
```

kpod can pull image by name is okay
```
[root@fedora27 cri-o]# kpod  pull redis:alpine
Trying to pull docker.io/library/redis:alpine...
Getting image source signatures
Copying blob sha256:1160f4abea84cbe2f316db6306839d2704f09a04af763ee493dd92cb066c0865
 1.90 MB / 1.90 MB [========================================================] 0s
Copying blob sha256:a8c53d69ca3aed47d1db25335f3b3c89f755dc18f177ae7a70c4c8f70f8edcbd
 1.22 KB / 1.22 KB [========================================================] 0s
Copying blob sha256:2dbffccae30ef7a74b938eaa2aaed4b067a15e62d0dd059a063bdf272defae8b
 7.99 KB / 7.99 KB [========================================================] 0s
Copying blob sha256:0a00d98b862d89b5296d56266387a533816a1490efc3aa3d6ae5ecc64eed0a1d
 7.72 MB / 7.72 MB [=======================================================] 10s
Copying blob sha256:6162f8e8bd54d523376aa6c0f9f01b85472a936837e945d59ce6befb07240ebc
 100 B / 100 B [============================================================] 0s
Copying blob sha256:ed931789deac842ebed5fa55c722548cf7384a6ed8ec1daf5a7d19b61dbf7ccd
 400 B / 400 B [============================================================] 0s
Copying config sha256:ed8544cc83deb9b120eec364cae7878483c496bd64948fde7815e65a57d04d3a
 4.68 KB / 4.68 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
[root@fedora27 cri-o]#
```

**Comment by feiskyer** [comment] 2017-12-08 04:37
@gouyang Didn't reproduce the problem. Does cri-o's gRPC api support pulling image without `docker.io/library` prefix?

**Comment by yanxuean** [comment] 2017-12-10 03:13
The crictl support to pull image without prefix. Maybe the reason is suffix.

**Comment by yanxuean** [comment] 2017-12-11 01:58
The returned error is not from cri-containerd. The cri-containerd wrap all error, I don't find the error info.
@gouyang  Are you sure that the crictl connected to cri-containerd? 
What are their version? Include crictl,cri-containerd.

**Comment by gouyang** [comment] 2017-12-11 03:14
crictl, kpod and crio are built from latest source code.

The latest results are:
```
[root@fedora libpod]# kpod pull busybox
error getting default registries to try: unable to parse the registries.conf file and the image name 'busybox' is incomplete.: Near line 9 (last key parsed ''): Bare keys cannot contain ':'.
# kpod pull redis:alpine
error getting default registries to try: unable to parse the registries.conf file and the image name 'redis' is incomplete.: Near line 9 (last key parsed ''): Bare keys cannot contain ':'.

[root@fedora libpod]# crictl pull busybox
FATA[0000] pulling image failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image 
```

There is no registries configured in /etc/crio/crio.conf, should it use `docker.io` by default when no one is set?

**Comment by yanxuean** [comment] 2017-12-11 05:41
It should be a issue of crio. The crictl only pass it to runtime. :)

**Comment by yanxuean** [comment] 2017-12-11 05:44
For crictl + cri-containerd + containerd
```
cloud@ubuntu:~$ sudo crictl rmi busybox
Deleted: docker.io/library/busybox:latest
cloud@ubuntu:~$ sudo crictl pull busybox
Image is update to date for sha256:6ad733544a6317992a6fac4eb19fe1df577d4dec7529efec28a5bd0edad0fd30
cloud@ubuntu:~$ sudo crictl images
IMAGE                            TAG                 IMAGE ID            SIZE
docker.io/library/busybox        latest              6ad733544a631       720kB
docker.io/library/redis          alpine              ed8544cc83deb       10.1MB
gcr.io/google_containers/pause   3.0                 320aedbfaad3d       312kB
```

**Comment by Random-Liu** [comment] 2017-12-11 19:12
@gouyang cri-o should support apply default image repository. If you use cri-containerd or dockershim, I believe both of them will work.

**Comment by feiskyer** [comment] 2017-12-12 01:35
> cri-o should support applying default image repository. 

Agreed. Let's close this issue since it is actually a cri-o specific problem.

**Closed by feiskyer** 2017-12-12 01:35 UTC
